<a href="https://colab.research.google.com/github/juanperez20/javascript/blob/main/ExtraccionDatosJuan_Perez_015_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Extraccion de datos de diversas fuentes

En este notebook explora diversas tecnicas para extraer datos de texto de diferentes  fuentes, un paso fundamental en el analisis de datos y proyectos de procesamiento. Nos basaremos en las recetas de libro ** Natural Language Processing Recipes.**

1. Archivos de texto plano
2. Documentos PDF
3. Documentos de Word (.docx)
4. Paginas web (Web Scraping)
5. APls
6. Base de datos
7. Hojas de calculo
8. Archivos XML y JSON

#Generacion de contenido de relleno
Pidele a tu bicho de confianza (ChatBot) que genere un acrosticocon su nombre que tenga una longitud de 1000 caracteres

In [1]:
texto_relleno = '''
Afectuosa, entregas cariño de manera sincera y especial a quienes quieres.
Noble, te preocupas por los demás y piensas mucho en cómo pueden sentirse.
Genuina, tienes una personalidad propia y prefieres mostrarte tal como eres.
Intuitiva, percibes pequeños detalles, gestos y emociones que otros no notan.
Exigente contigo misma, buscas mejorar constantemente, aunque a veces seas dura contigo.

Bondadosa, valoras los detalles pequeños y las muestras de cariño.
Luchadora, aunque tengas momentos de inseguridad, encuentras fuerzas para continuar.
Analítica, piensas mucho las cosas y buscas diferentes posibilidades antes de decidir.
Nerviosa a veces, porque tu mente puede imaginar muchos escenarios.
Cariñosa, construyes vínculos profundos y valoras sentirte querida y comprendida.
Optimista, incluso cuando algo se complica, conservas las ganas de aprender, crecer y demostrarte que puedes lograr lo que te propones.'''

## Conexion de Google Drive y Creacion de un Directorio de Trabajo

Antes de empezar escrucial que conectemos nuestro entrono de Colab con Google Drive. Esto nos permitira guardar y acceder a nuestro archivo de manera persistente. Ademas, crearemos un directorio unico para todo nuestro trabajo en este notebook.

**Instrucciones:**
1. **Conectar Google Drive:** Ejecuta la siguiente celda de codigo para montar tu Google Drive en Colab. Asegurate de seguir las indicaciones para autenticarte.

2. **Crear un Directorio Unico:** Una vez conectado tu Drive, navegaremos a la carpeta ``My Drive`` y crearemos un directorio con un nombre que incluya su nombre y la fecha (p.e : mi_nombre_ExtraccionDatos_AAAAMMDD) .

**Ejemplo de nombre de directorio:**
``AngieBlanco_ExtraccionDatos_20260922``

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import os
base_drive_path = "/content/drive/MyDrive"

nombre_directorio_unico = "juanPerez_ExtraccionDatos_20260902"
directorio_trabajo = os.path.join(base_drive_path, nombre_directorio_unico)
if not os.path.exists(directorio_trabajo):
  os.makedirs(directorio_trabajo)
  print(f"directorio credo: {directorio_trabajo}")
else :
  print(f"el directorio ya existe{directorio_trabajo}")
os.chdir(directorio_trabajo)
print(f"directorio de trabajo actualizado: {os.getcwd()}")

el directorio ya existe/content/drive/MyDrive/juanPerez_ExtraccionDatos_20260902
directorio de trabajo actualizado: /content/drive/MyDrive/juanPerez_ExtraccionDatos_20260902

##Preparacion del entorno
Primero instaaremos las librerias necesarias para las diferentes recetas

In [5]:
!pip install PyPDF2 python_docx beautifulsoup4 requests pandas openpyxl reportlab

print("Bibliotecas instaladas con exito.")

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Collecting python_docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Collecting reportlab
  Downloading reportlab-5.0.1-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from python_docx) (6.1.3)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.13/dist-packages (from python_docx) (4.16.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.13/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 5.5 MB/s eta 0:00:00
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 20.0 MB/s eta 0:00:00
Downloading reportlab-5.0.1-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 49.9 MB/s eta 0:00:00
Installing collected packages: reportlab, python_docx, PyPDF2
Successfully installed PyPDF2-3.0.1 python_docx-1.2.0 reportlab-5.0.1
Bibliotecas instaladas con exito.

##Receta 1 :Extraccion de Textos de Archivos de Texto Plano (.txt)

Esta receta muestra como leer contenido directamente de un archivo de texto simple. Esla forma mas basica de extrccion de datos textuales

In [6]:
#Genere un archivo de texto de prueba con el texto de relleno
nombre_archivo_txt = "JuanPerez_20260929.txt"
contenido_txt = texto_relleno

#Guardar el contenido en un archivo de texto
with open(nombre_archivo_txt, "w", encoding="utf-8") as archivo:
  archivo.write(contenido_txt)

f"Archivo de texto creado={nombre_archivo_txt}"

'Archivo de texto creado=JuanPerez_20260929.txt'

In [7]:
# Leer el contenido del archivo de texto

with open(nombre_archivo_txt, "r", encoding="utf-8") as archivo:
  contenido_leido = archivo.read()

# Imprimir el contenido
print("\n--- Contenido extraido (primeros 300 caracteres) ---")
print(contenido_leido[:300] + "...")
print("\nLongitud total del texto extraido:", len(contenido_leido),"caracteres.")

--- Contenido extraido (primeros 300 caracteres) ---

Afectuosa, entregas cariño de manera sincera y especial a quienes quieres.
Noble, te preocupas por los demás y piensas mucho en cómo pueden sentirse.
Genuina, tienes una personalidad propia y prefieres mostrarte tal como eres.
Intuitiva, percibes pequeños detalles, gestos y emociones que otros no n...

Longitud total del texto extraido: 920 caracteres.

##Receta 2: Extraccion de Textos de Documentos PDF
los archivos de PDF son comunes para documnetos formales. Extraer textos de ellos requieren bibliotecas especificas que puedan interpretar su estructura.

In [8]:
#Generar un archivo PDF de prueba con el texto de relleno usado ReportLab
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

nombre_archivo_pdf = "JuanPerez_20260929.pdf"
contenido_pdf = "Este es mi PDF de prueba + mi texto de relleno personalizado" + texto_relleno

c = canvas.Canvas(nombre_archivo_pdf, pagesize=letter)
c.setFont("Helvetica", 12)
c.drawString(72, 750, "Ejemplo de Documento PDF para la Extraccion de Datos")

# Dividir el contenido para ajustar en la pagina
y_position = 730
line_height = 14
for line in contenido_pdf.split('\n'):
  c.drawString(72, y_position, line)
  y_position -= 20
  if y_position < 50:
    c.showPage()
    y_position = 750
    c.setFont("Helvetica", 12)

c.save()

print(f"Archivo PDF creado: {nombre_archivo_pdf} con exito.")

Archivo PDF creado: JuanPerez_20260929.pdf con exito.

In [10]:
#Extraer texto de un PDF

import PyPDF2

texto_PDF_extraido = ""

try:
  with open(nombre_archivo_pdf, "rb") as archivo_pdf:
    lector_pdf = PyPDF2.PdfReader(archivo_pdf)
    for page in lector_pdf.pages:
      texto_pdf_extraido += page.extract_text() + "\n"

except Exception as e:
  print(f"Error al extraer texto del PDF: {e}")
  texto_pdf_extraido = "Error al extraer texto de PDF."

print("\n--- Contenido extraido (primeros 300 caracteres) ---")
print(texto_PDF_extraido[:300] + "...")
print("\nLongitud total del texto extraido:", len(texto_pdf_extraido), "caracteres.")

Error al extraer texto del PDF: name 'texto_pdf_extraido' is not defined

--- Contenido extraido (primeros 300 caracteres) ---
...

Longitud total del texto extraido: 30 caracteres.

##Receta 3:Extraccion de Texto de Documentos Word (.docx)

los documentos de word son otra forma comun de texto estructurado. La libreria ``python-docx`` permite acceder a su contenido.

In [9]:
#Genere un archivo de prueba con el texto relleno

from docx import Document

nombre_archivo_docx = "JuanPerez_20260929.docx"
contenido_docx = "Este es mi documento Word de prueba + mi texto de relleno personalizado." + texto_relleno

documento = Document()
documento.add_heading("Documento Word de Prueba" + "Angie Blanco", level=1)
documento.add_paragraph(contenido_docx)
documento.save(nombre_archivo_docx)

print(f"Archivo Word {nombre_archivo_docx} creado con exito.")

Archivo Word JuanPerez_20260929.docx creado con exito.

In [11]:
#Extraer texto de un documento Word

texto_docx_extraido = []

try:
  documento = Document(nombre_archivo_docx)
  for paragraph in documento.paragraphs:
    texto_docx_extraido.append(paragraph.text)
except Exception as e:
  print(f"Error al extraer texto del documento")

print("\n--- Contenido extraido (primeros 300 caracteres) ---")
print(texto_docx_extraido[1][:300] + "...")
print("\nLongitud total del texto extraido:", len(texto_docx_extraido[0] + texto_docx_extraido[1]), "caracteres.")

--- Contenido extraido (primeros 300 caracteres) ---
Este es mi documento Word de prueba + mi texto de relleno personalizado.
Afectuosa, entregas cariño de manera sincera y especial a quienes quieres.
Noble, te preocupas por los demás y piensas mucho en cómo pueden sentirse.
Genuina, tienes una personalidad propia y prefieres mostrarte tal como eres.
...

Longitud total del texto extraido: 1028 caracteres.

##Receta 4 : Extraccion de texto de Paginas Web (Web Scraping)

el Web Scraping nos permite extraer informacion directamete de sitios web. Usaremos ``requests`` para obtener el HTML y ``BeautifulSoup`` para parsearlo.

###Entendiendo la estructura Basica de HTML para Web Scraping

Para extraer información de una página web, primero necesitamos entender cómo está estructurada. HTML (HyperText Markup Language) es el lenguaje estándar para crear páginas web y está compuesto por una serie de elementos o ``etiquetas`` anidadas que definen el contenido y su organización.   
Consideremos la página de ejemplo ``http://quotes.toscrape.com/``. Si inspeccionas está página (usando las herramientas de desarrollo de tu navegador ``F12``) verás una estructura similar a la siguiente:

```html
<div class="quote">
 <span class="text" itemprop="text">"La vida es lo que pasa mientras estás ocupado haciendo otros planes."</span>
 <span>
  by <small class="author" itemprop = "author"> John Lennon</small>
  <a href="/author/John-Lennon">(más)</a>
 </span>
 <div class="tags">
  Etiquetas: <a class="tag" href="/tag/life/" (...) >life</a>
  <a class="tag" href="/tag/live" (...) >live</a>
 </div>
</div>
```

**Elementos claves**

* **Etiquetas (``<div>``, ``<span>``, ``<small>``, ``<a>``):** Indica el tipo de contenido. Por ejemplo, ``<div>`` suele ser contenedores, ``<span>`` para texto en línea, ``<small>`` para texto más pequeño y ``<a>`` para enlaces.

  * **Atributos (``class``, ``href``, ``itemprop``):** Proporcionann información adicional sobre etiquetas. Son cruciales para seleccionar elementos específicos:
  * ``class="quote"``: Indica que este ``div`` es un bloque de cita.
  * ``itemprop="text"``: Define el texto de la cita.
  * ``class="author"``: Identifica el autor.
  * ``href="/author/John-Lennon"``: Contiene la URL del perfil del autor.

Cuando hacemos web scraping nuestro objetivo es localizar estas etiquetas y atributos específicos para estrar la información deseada

In [12]:
import requests
from bs4 import BeautifulSoup

url_ejemplo = "http://quotes.toscrape.com/" # Una página diseñada para practicar Web Scraping

texto_web_extraido = ""

try:
    response = requests.get(url_ejemplo)
    response.raise_for_status() # Lanza una excepción para errores HTTP
    soup = BeautifulSoup(response.text, "html.parser")

    # Extraer el texto de todas las citas y autores
    citas = soup.find_all("span", class_="text")
    autores = soup.find_all("small", class_="author")

    for i in range(len(citas)):
      texto_web_extraido += f"Cita: {citas[i].get_text()}\n"
      texto_web_extraido += f"Autor: {autores[i].get_text()}\n\n"
except requests.exceptions.RequestException as e:
    print(f"Error al acceder a la página web: {e}")
    texto_web_extraido = "Error al acceder a la página web."
except Exception as e:
    print(f"Error al extraer el texto de la página web: {e}")
    texto_web_extraido = "Error al extraer texto de la página web."

print("\n--- Contenido extraído (primeros 300 caracteres) ---")
print(texto_web_extraido[:300] + "...")
print("\nLongitud total del texto extraído de la web:", len(texto_web_extraido), "carecteres.")

--- Contenido extraído (primeros 300 caracteres) ---
Cita: “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
Autor: Albert Einstein

Cita: “It is our choices, Harry, that show what we truly are, far more than our abilities.”
Autor: J.K. Rowling

Cita: “There are only two ways to live yo...

Longitud total del texto extraído de la web: 1192 carecteres.

Admás de HTML las páginas web utilizan CSS para definir su apariencia y fomato (colores, fuentes, diseños y etc). Aunque HTML estructura el contenido CSS le da estilo. Los selectores CSS (como ``class="text"`` o ``id="main-content"``) son fundamentales en Web Scraping ya que nos permiten identificar y seleccionar elementos específicos basándonos en cómo están estilizados o agrupados, facilitando la extracción precisa de los datos.

**Nota Importante sobre Páginas Dinámicas:** Es crucial entender que ``requests`` y ``BeautifulSoup`` son excelentes para páginas web estáticas donde el contenido HTML ya está presente en la respuesta inicial del servidor. Sin embargo muchas páginas modernas cargan su contenido de forma dinámica utilizando JavaScript. En estos casos ``requests`` solo verá el HTML inicial (a menudo vacío o con plantillas) y ``BeautifulSoup`` no podrá extraer el contenido final. Para estas situaciones, herramientas como **Selenium** (un software para la automatización de navegadores web) son necesarias ya que simulan la interacción de un usuario real en un navegador permitiendo que el JavaScript se ejecute y el contenido dinámico se cargue antes de la exracción. Por ahora no introduciremos ``Selenium`` en el código pero es fundamental conocer esta limitación ya su posible solución.

**Consideraciones Éticas:** Es fundamental respetar lo ``robots.txt`` de los sitios web y sus términos de servicio. Para este ejemplo usamos una página pública de ejemplo.

## Receta 5: Extraccion de Datos de APIs
Las APIs (Interfaces de Programación de Aplicaciones) son una forma estructurada de acceder a los datos. Usaremos una API pública para demostra la extracción de datos JSON.

**Operaciones Comunes de APIs (Verbos HTTP):** Las APIs suelen seguir el protocolo HTTP y utilizan "verbos" o métodos para indicar el tipo de operación que se desea realizar sobre un recurso:

* **GET:** Se utiliza para solicitar datos de un recurso específico (Ejemplo: obtener información de un post).
* **POST:** Se utiliza para enviar datos y crear un nuevo recurso. (Ejemplo: crear un nuevo usuario).
* **PUT:** Se utiliza para enviar datos y actualizar un recurso existente, reemplazándolo completamente.
* **DELETE:** Se utiliza para eliminar un recurso específico.
* **PATCH:** Se utiliza para aplicar modificaciones parciales a un recurso.

**Estructura Básica de un Documento JSON:** JSON (JavaScript Object Notation) es un formato ligero para el intercambio de datos. Es fácil de leer y escribir para los humanos y fácil de parcear ya generar para las máquinas. Su estructura se basa en dos tipos:

* **Colecciones de pares nombre/valor (objetos):** Representados por corchetes ``{}``. Un objeto es una lista no ordenada de pares ``"clave": valor``. Las claves deben ser cadenas de texto.

```json
{
"nombre" : "Juan",
"edad" : 30,
"ciudad" : "Bogotá"
}
```

* **Listas ordenadas de valores (arrays):** Representadas por llaves ``[]``. Un array es una secuencia de valores.

```json
[
 "manzana",
 "banano",
 "limón"
]
```
Los valores pueden ser cadenas de texto, números, booleanos (``true``/``false``), null, objetos o arrays. Esta flexibilidad permite representar estructuras de datos complejas.   Para este ejemplo utilizaremos la API pública de
``JSONPlaceholder`` que proporciona datos ficticios de prueba.

In [13]:
import requests
import json

url_api = "https://jsonplaceholder.typicode.com/posts/1" # Un post de ejemplo

datos_api_extraidos = {}

try:
    response = requests.get(url_api)
    response.raise_for_status()
    datos_api_extraidos = response.json()

except requests.exceptions.RequestException as e:
    print(f"Error al acceder a la API: {e}")
    datos_api_extraidos = {"Error": "Error al acceder a la API"}

except json.JSONDecodeError as e:
    print(f"Error al decodificar JSON de la API: {e}")
    datos_api_extraidos = {"Error": "Error al decodificar JSON"}

print("\n --- Datos Extraídos de la API ---")
print(json.dumps(datos_api_extraidos,indent=2))
print(f"\nTipo de datos extraídos: {type(datos_api_extraidos)}")

 --- Datos Extraídos de la API ---
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

Tipo de datos extraídos: <class 'dict'>

## Receta 6: Extracción de Datos de Bases de Datos

Las bases de datos (BD) permiten almacenar y organizar información para que pueda ser consultada, actualizada y utilizada posteriormente por diferentes aplicaciones.

En una base de datos relacional la información se organiza principalmente en tablas compuestas por filas y columnas. Una base de datos puede contener varias tablas relacionadas entre sí, por lo que es importante no confundir una tabla con la base de datos completa.

Para trabajar con bases de datos relacionales se utiliza principalmente ``SQL`` (Structured Query Language) un lenguaje que permite crear estructuras, almacenar información y realizar consultas sobre los datos.

En esta receta utilizaremos ``SQLite`` un sistema de base de datos relacional ligero que puede almacenar toda una base de datos en un único archivo. Python incorpora el módulo sqlite3 que nos permitirá crear la base de datos, almacenar algunos datos y posteriormente extraerlos.

### Crear nuestra base de datos

Antes de extraer información necesitamos una fuente que la contenga. Al igual que en las recetas anteriores creamos archivos .txt, .pdf o .docx, ahora crearemos un archivo que contendrá nuestra base de datos.

Utilizaremos ``sqlite3.connect()`` para conectarnos a **SQLite**. Si el archivo indicado todavía no existe, SQLite lo creará automáticamente.

In [14]:
import sqlite3
import pandas as pd

# Nombre del archivo que contendrá nuestra base de datos
nombre_db = "AngieBlanco_20261006.db"
# Crear o conectarse a la base de datos
conn = sqlite3.connect(nombre_db)

print(f"Base de datos '{nombre_db}' creada/conectada con éxito")

Base de datos 'AngieBlanco_20261006.db' creada/conectada con éxito

### Crear una tabla para almacenar los datos

Nuestra base de datos ya existe pero todavía no contiene información. Necesitamos definir dónde almacenaremos los datos.

Crearemos una tabla llamada articulos con tres columnas:

* id: indentificador único de cada artículo.
* titulo: título del artículo.
* contenido: texto asociado al artículo

La instrucción **SQL CREATE TABLE** permite crear una nueva tabla y definir las columnas que formarán parte de ella.

In [15]:
# Crear un cursos para ejecutar instrucciones SQL
cursor = conn.cursor()

# Crear la tabla articulos
cursor.execute('''
CREATE TABLE IF NOT EXISTS articulos (
 id INTEGER PRIMARY KEY,
 titulo TEXT NOT NULL,
 contenido TEXT
)
''')

# Guardar los cambios
conn.commit()

print("Tabla 'articulos' creada con éxito.")

Tabla 'articulos' creada con éxito.

### Insertar datos en la tabla

Ahora tenemos una base de datos y una tabla pero la tabla se encuentra vacía.

Crearemos algunos registros de prueba y utilizaremos la instrucción **SQL INSERT** para almacenarlos. En este ejemplo cada elemento de la lista representa una fila que será incorporada en la tabla articulos.

In [16]:
# Datos de prueba
datos_prueba = [
    (1,
     "La importancia del Data Science",
     "El data science es crucial para la toma de decisiones modernas."),
    (2,
     "PNL: De la teoría a la práctica",
     "El procesamiento de lenguaje natural ha avanzado enormemente con el deep learning."),
    (3,
     "Web Scraping Ético",
     "Es fundamental seguir buenas prácticas al realizar web scraping.")
]

# Insertar los registros en la tabla
cursor.executemany(
    "INSERT OR IGNORE INTO articulos (id, titulo, contenido) VALUES (?, ?, ?)",
    datos_prueba
)

# Guardar los cambios realizados
conn.commit()

print(f"{len(datos_prueba)} registros procesados en la tabla 'articulos'.")

3 registros procesados en la tabla 'articulos'.

### Extraer datos mediante una consulta SQL

Ahora sí llegamos al objetivo principal de esta receta: extraer información almacenada en una base de datos.

Para consultar datos utilizaremos la instrucción **SQL SELECT**. Podemos indicar qué columnas queremos recuperar y de qué tabla deben obtenerse. Por ejemplo:

```sql
SELECT titulo, contenido
FROM articulos;

Esta consulta puede leerse prácticamente como una instrucción:

**"Seleccionar las columnas titulo y contenido de la tabla articulos"**

Ejectutaremos esta consulta desde Python y recuperaremos las filas encontradas

In [17]:
# Ejecutar una consulta SQL
cursor.execute('''
SELECT titulo, contenido
FROM articulos
''')

# Recuperar todos los registros encontrados

filas = cursor.fetchall()

print("--- Datos Extraídos de la Base de Datos ---")

for fila in filas:
    print(f"Título: {fila[0]}")
    print(f"Contenido: {fila[1]}")
    print("---")

print(f"\n Nñumero de registros extraídos: {len(filas)}")

--- Datos Extraídos de la Base de Datos ---
Título: La importancia del Data Science
Contenido: El data science es crucial para la toma de decisiones modernas.
---
Título: PNL: De la teoría a la práctica
Contenido: El procesamiento de lenguaje natural ha avanzado enormemente con el deep learning.
---
Título: Web Scraping Ético
Contenido: Es fundamental seguir buenas prácticas al realizar web scraping.
---

 Nñumero de registros extraídos: 3

### Extraer datos directamente con pandas

En proyectos de análisis de datos normalmente necesitamos llevar la información consultada a una estructura que podamos explorar y transformar posteriormente.

La librería ``pandas`` puede ejecutar consultas sql y almacenar directametne su resultado en un **DataFrame**.

Un **DataFrame** es una estructur de datos bidimensional organizada en filas y columnas, similar visualmente a una tabla de una base de datos o una hoja de cálculo. Cada columna puede representar una variable o característica y cada fila una observación o registro.

| id | titulo | contenido |
|---|---|---|
| 1 | La Importancia del Data Science | El data science es crucial... |
| 2 | PNL: De la Teoría a la Práctica | El procesamiento de lenguaje... |
| 3 | Web Scraping Ético | Es fundamental seguir... |

Aunque visualmente se parece a una tabla, el DataFrame es un objeto de Python sobre el cual podemos realizar posteriormente operaciones de selección, filtrado, transformación, limpieza y análisis de datos.

``pandas`` puede ejecutar una consulta SQL y almacenar directamente el resultado en un DataFrame

In [18]:
# Consulta SQL

consulta = '''
SELECT id, titulo, contenido
FROM articulos
'''

# Extraer los datos directamente a un DataFrame

df = pd.read_sql_query(consulta, conn)

print("--- Datos Extraídos como DataFrame")

df

--- Datos Extraídos como DataFrame

,id,titulo,contenido
0,1,La importancia del Data Science,El data science es crucial para la toma de dec...
1,2,PNL: De la teoría a la práctica,El procesamiento de lenguaje natural ha avanza...
2,3,Web Scraping Ético,Es fundamental seguir buenas prácticas al real...

In [19]:
#Consulte las dimensiones del DF
df.shape

(3, 3)

### Cerrar la conexión

Cuando terminamos de trabajar con una base de datos es una buena práctica cerrar la conexión. Esto libera los recursos utilizados y finaliza correctamente nuestra comunicación con la base de datos.

In [20]:
# Cerrar la conexión con la base de datos.
conn.close()

print("Conexión con la base de datos cerrada correctamente.")

Conexión con la base de datos cerrada correctamente.

## Receta 7: Extracción de Datos de Hojas de Cálculo (CSV/Excel)

Las hojas de cálculo son un formato muy común para compartir datos estructurados. Usaremos ``pandas`` para leer archivos **CSV y Excel**.

In [21]:
import pandas as pd

# Generar un archivo CSV de prueba
nombre_archivo_csv = "AngieBlanco_20261008.csv"
datos_csv = {
    "Producto" : ["Laptop", "Mouse", "Teclado", "Monitor"],
    "Precio" : [12000, 25, 75, 300],
    "Stock" : [10, 50, 30, 15]
}
df_csv = pd.DataFrame(datos_csv)
df_csv.to_csv(nombre_archivo_csv, index=False)
df_csv

  Producto  Precio  Stock
0   Laptop   12000     10
1    Mouse      25     50
2  Teclado      75     30
3  Monitor     300     15

In [23]:
# Generar un archivo Excel de prueba
nombre_archivo_excel = "JuanPerez_20260929.xlsx"
df_excel = pd.DataFrame(datos_csv)
df_excel.to_excel(nombre_archivo_excel, index=False)
df_excel

  Producto  Precio  Stock
0   Laptop   12000     10
1    Mouse      25     50
2  Teclado      75     30
3  Monitor     300     15

In [24]:
# Extraer datos de CSV

datos_csv_extraidos = pd.read_csv(nombre_archivo_csv)
datos_csv_extraidos

  Producto  Precio  Stock
0   Laptop   12000     10
1    Mouse      25     50
2  Teclado      75     30
3  Monitor     300     15

In [25]:
# Extraer datos de Excel

datos_excel_extraidos = pd.read_excel(nombre_archivo_excel)
datos_excel_extraidos

  Producto  Precio  Stock
0   Laptop   12000     10
1    Mouse      25     50
2  Teclado      75     30
3  Monitor     300     15

## Receta 8: Extracción de Datos de Archivos XML y JSON

**XML y JSON** son formatos comunes para el intercambio de datos estructurados. Python tiene módulos nativos para trabajar con ambos.

**XML** nos es un lenguaje con un vocabulario fijo, sino un conjunto de reglas para crear lenguajes de marcado. **SVG y RSS** son dos vocabularios especializados basados en **XML** pero resuelven problemas completamente diferentes.

**Relación entre tipos de estructuras**

| Tecnología | Relación | ¿Para qué sirve? |
|---|---|---|
| **HTML** | Lenguaje de marcado relacionado históricamente con SGML | Estructurar contenido de páginas web |
| **XML** | Lenguaje de marcado derivado de SGML | Representar e intercambiar datos estructurados |
| **SVG** | Lenguaje de gráficos basado en XML | Representar gráficos vectoriales |
| **RSS** | Formato de sindicación basado en XML | Distribuir contenido actualizado |
| **JSON** | Formato de intercambio de datos independiente de XML | Representar e intercambiar datos estructurados de forma ligera |

In [26]:
import json
import xml.etree.ElementTree as ET

# Generar un archivo JSON de prueba
nombre_archivo_json = "JuanPerez_20260929.json"
datos_json = {
    "libro" :{
        "titulo" : "Aprendiendo Python",
        "autor" : "John Doe",
        "generos" : ["Programación", "Educación"],
        "disponible" : True
    }
}
with open(nombre_archivo_json, "w", encoding="utf-8") as archivo:
    json.dump(datos_json, archivo, indent=2)

print(f"Archivo '{nombre_archivo_json}' creado con éxito.")

Archivo 'JuanPerez_20260929.json' creado con éxito.

In [27]:
# Generar un archivo XML de prueba
nombre_archivo_xml = "JuanPerez_20260929.xml"
root = ET.Element("libros")
libro = ET.SubElement(root, "libro")
titulo = ET.SubElement(libro, "titulo")
titulo.text = "Data Science con Python"
autor = ET.SubElement(libro, "autor")
autor.text = "Jane Smith"
publicacion = ET.SubElement(libro, "publicacion")
publicacion.text = "2022"

tree = ET.ElementTree(root)
with open(nombre_archivo_xml, "wb") as f:
    tree.write(f, encoding="utf-8", xml_declaration=True)

print(f"Archivo '{nombre_archivo_xml}' creado con éxito.")

Archivo 'JuanPerez_20260929.xml' creado con éxito.

In [29]:
# Extraer datos de JSON

datos_json_extraidos = {}
try:
    with open(nombre_archivo_json, "r", encoding="utf-8") as f:
        datos_json_extraidos = json.load(f)
except Exception as e:
    print(f"Error al leer el archivo JSON: {e}")
    datos_json_extraidos = {"Error": "Error al leer el archivo JSON"}

print("--- Datos Extraídos de JSON ---")
print(json.dumps(datos_json_extraidos, indent=2))

--- Datos Extraídos de JSON ---
{
  "libro": {
    "titulo": "Aprendiendo Python",
    "autor": "John Doe",
    "generos": [
      "Programaci\u00f3n",
      "Educaci\u00f3n"
    ],
    "disponible": true
  }
}

In [28]:
# Extraer datos de XML
datos_xml_extraidos = []
try:
    tree = ET.parse(nombre_archivo_xml)
    root = tree.getroot()
    for libro in root.findall("libro"):
        titulo = libro.find("titulo").text
        autor = libro.find("autor").text
        publicacion = libro.find("publicacion").text
        datos_xml_extraidos.append({"titulo": titulo, "autor": autor, "publicacion": publicacion})
except Exception as e:
    print(f"Error al leer el archivo XML: {e}")
    datos_xml_extraidos =[{"error": "Error al leer XML"}]

print("\n --- Datos Extraídos de XML ---")
for item in datos_xml_extraidos:
    print(item)

 --- Datos Extraídos de XML ---
{'titulo': 'Data Science con Python', 'autor': 'Jane Smith', 'publicacion': '2022'}